export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_TASK = "GET_PROJECT_TASK";
export const GET_SINGLE_PROJECT_TASK = "GET_SINGLE_PROJECT_TASK";
export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";
export const UPDATE_PROJECT_TASK = "UPDATE_PROJECT_TASK";